const questions = [
  "Do you believe we need to change the way the Chicago City Council draws its ward maps to ensure more accurate representation and participation of communities?",
  "Do you support an amendment to state statute to change the redistricting process to create an independent resident commission that reflects the diversity (age, gender, race, and socioeconomic) of Chicago to be tasked with drawing Chicago’s ward maps going forward?",
  "Do you support changes to the current ward mapping process that would allow more meaningful time for Chicago residents to provide feedback on proposed maps? Do you support requiring evidence that shows how residents’ feedback was considered?",
  "Do you support changes to the current redistricting process that would provide resources for residents and community organizations to analyze proposed ward maps, propose their own maps, and offer testimony about their communities? What changes would you support so that residents receive feedback from officials when they submit their own maps?",
  "Municipal redistricting law in Illinois currently counts incarcerated people as residents at their place of incarceration rather than at their last-known home address for purposes of drawing new ward maps. Do you support expanding prison gerrymandering reform to local ward redistricting? This would require that state agencies prepare and share redistricting data that lists incarcerated people at their last residential addresses, rather than at the addresses of the facilities where people are incarcerated at the time of the census.",
  "Would you support additional redistricting reform measures for state and congressional districts? Why or why not?",
  "COMPLY WITH THE U.S. CONSTITUTION\n\nThe process must be in accordance with the requirements of the U.S. Constitution. All persons -- regardless of age, citizenship, immigration status, ability, or eligibility to vote – should be accurately counted through the Census. In accordance with the U.S. Constitution, districts should be populated equally, as nearly as is practicable.",
  "COMPLY WITH FEDERAL AND STATE VOTING RIGHTS ACT\n\nThe process must emphasize representation and be fully compliant with both the federal Voting Rights Act (VRA) and all state voting rights laws, including the Illinois Voting Rights Act. The letter and the spirit of the VRA should be reflected in redistricting to protect the rights of voters of color. To advance these foundational goals, redistricting decision-makers should exercise their latitude under the law to create majority-minority, coalition, and influence districts.",
  "MAXIMIZE VOTER CHOICE, ELECTORAL CANDIDACY AND COMPETITIVENESS\n\nThe process should result in maximizing voter choice, encouraging electoral candidacy, and enhancing electoral competitiveness.",
  "RECOGNIZE AND PRESERVE COMMUNITIES OF INTEREST\n\nThe process should give consideration to true communities of interest. To the extent possible, but secondary to the protection of voting rights, populations with common social, ethnic or economic interests should have unified representation.",
  "ACCURATELY INCLUDE PERMANENT RESIDENCE OF ALL ILLINOISANS\n\nThe process must accurately represent the permanent residence of all Illinoisans. All persons residing away from their permanent residence, such as students, incarcerated individuals, and missionaries, should be counted at their home addresses regardless of Census counting rules. The Census should be encouraged to expand its exceptions to the usual residence rule to include incarcerated individuals, as well as students, missionaries, and overseas Americans.",
  "COMPRISE AND UPHOLD A TRANSPARENT AND ACCOUNTABLE PROCESS\n\nThe process must be transparent and accountable. Meetings of decision-makers and their legal, political, and mapping consultants must be open and accessible to the public to the greatest extent possible. The criteria used to draw maps must be objective, clear and justifiable, and districts must be drawn to offer voter choice. Communications related to the redistricting process should be subject to the Open Meetings Act and the Freedom of Information Act. Clear conflict-of-interest rules must be adopted and applied.",
  "PROVIDE FOR OPEN, FULL, AND MEANINGFUL PUBLIC PARTICIPATION\n\nThe process must allow for meaningful public participation and have the confidence of the public. Opportunities for public education and engagement must be provided, including opportunities to offer comment and amend draft maps. Redistricting bodies must provide data, tools, and ways for the public to have direct input into and affect the specific plans under consideration.",
  "Any final thoughts or points you would like to make on the subjects of gerrymandering and redistricting reform?",
];

export default questions;
